// Generated by CoffeeScript 1.10.0
(function() {
  var api, app, bodyParser, express, logger, path, routes;

  express = require('express');

  path = require('path');

  logger = require('morgan');

  bodyParser = require('body-parser');

  routes = require('./routes/index');

  api = require('./routes/api');

  app = express();

  app.use(logger('dev'));

  app.use(bodyParser.json());

  app.use(bodyParser.urlencoded({
    extended: false
  }));

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.set('x-powered-by', false);

  app.use('/', routes);

  app.use('/api', api);

  app.use(function(req, res, next) {
    var err;
    err = new Error('Not Found');
    err.status = 404;
    return next(err);
  });

  if (app.get('env') === 'development') {
    app.use(function(err, req, res, next) {
      res.status(err.status || 500);
      return res.render('error', {
        message: err.message,
        error: err
      });
    });
  }

  app.use(function(err, req, res, next) {
    res.status(err.status || 500);
    return res.json({
      error: err.massage
    });
  });

  module.exports = app;

}).call(this);
