// Generated by CoffeeScript 1.10.0
(function() {
  var express, models, router;

  express = require('express');

  router = express.Router();

  models = require('../models');

  router.get('/tasks', function(req, res, next) {
    return models.Task.findAll().then(function(tasks) {
      return res.json(tasks || []);
    });
  });

  router.get('/tasks/:id', function(req, res, next) {
    return models.Task.findById(req.params.id).then(function(task) {
      return res.json(task || {});
    });
  });

  router.post('/tasks', function(req, res, next) {
    return models.Task.create(req.body).then(function(created_obj) {
      return res.json(created_obj);
    });
  });

  router["delete"]('/tasks/:id', function(req, res, next) {
    return models.Task.destroy({
      where: {
        id: req.params.id
      }
    }).then(function(deleted_obj) {
      return res.json({
        id: req.params.id
      });
    });
  });

  module.exports = router;

}).call(this);
